package com.njsh.reelssaver.api.format.instagram

import com.google.gson.annotations.SerializedName


data class ShortcodeMedia (

  @SerializedName("__typename"                      ) var _typename                   : String?                     = null,
  @SerializedName("id"                              ) var id                          : String?                     = null,
  @SerializedName("shortcode"                       ) var shortcode                   : String?                     = null,
  @SerializedName("dimensions"                      ) var dimensions                  : Dimensions?                 = Dimensions(),
  @SerializedName("gating_info"                     ) var gatingInfo                  : String?                     = null,
  @SerializedName("fact_check_overall_rating"       ) var factCheckOverallRating      : String?                     = null,
  @SerializedName("fact_check_information"          ) var factCheckInformation        : String?                     = null,
  @SerializedName("sensitivity_friction_info"       ) var sensitivityFrictionInfo     : String?                     = null,
  @SerializedName("sharing_friction_info"           ) var sharingFrictionInfo         : SharingFrictionInfo?        = SharingFrictionInfo(),
  @SerializedName("media_overlay_info"              ) var mediaOverlayInfo            : String?                     = null,
  @SerializedName("media_preview"                   ) var mediaPreview                : String?                     = null,
  @SerializedName("display_url"                     ) var displayUrl                  : String?                     = null,
  @SerializedName("display_resources"               ) var displayResources            : ArrayList<DisplayResources> = arrayListOf(),
  @SerializedName("accessibility_caption"           ) var accessibilityCaption        : String?                     = null,
  @SerializedName("dash_info"                       ) var dashInfo                    : DashInfo?                   = DashInfo(),
  @SerializedName("has_audio"                       ) var hasAudio                    : Boolean?                    = null,
  @SerializedName("video_url"                       ) var videoUrl                    : String?                     = null,
  @SerializedName("video_view_count"                ) var videoViewCount              : Int?                        = null,
  @SerializedName("video_play_count"                ) var videoPlayCount              : Int?                        = null,
  @SerializedName("is_video"                        ) var isVideo                     : Boolean?                    = null,
  @SerializedName("tracking_token"                  ) var trackingToken               : String?                     = null,
  @SerializedName("upcoming_event"                  ) var upcomingEvent               : String?                     = null,
  @SerializedName("edge_media_to_tagged_user"       ) var edgeMediaToTaggedUser       : EdgeMediaToTaggedUser?      = EdgeMediaToTaggedUser(),
  @SerializedName("edge_media_to_caption"           ) var edgeMediaToCaption          : EdgeMediaToCaption?         = EdgeMediaToCaption(),
  @SerializedName("can_see_insights_as_brand"       ) var canSeeInsightsAsBrand       : Boolean?                    = null,
  @SerializedName("caption_is_edited"               ) var captionIsEdited             : Boolean?                    = null,
  @SerializedName("has_ranked_comments"             ) var hasRankedComments           : Boolean?                    = null,
  @SerializedName("like_and_view_counts_disabled"   ) var likeAndViewCountsDisabled   : Boolean?                    = null,
  @SerializedName("edge_media_to_parent_comment"    ) var edgeMediaToParentComment    : EdgeMediaToParentComment?   = EdgeMediaToParentComment(),
  @SerializedName("edge_media_to_hoisted_comment"   ) var edgeMediaToHoistedComment   : EdgeMediaToHoistedComment?  = EdgeMediaToHoistedComment(),
  @SerializedName("edge_media_preview_comment"      ) var edgeMediaPreviewComment     : EdgeMediaPreviewComment?    = EdgeMediaPreviewComment(),
  @SerializedName("comments_disabled"               ) var commentsDisabled            : Boolean?                    = null,
  @SerializedName("commenting_disabled_for_viewer"  ) var commentingDisabledForViewer : Boolean?                    = null,
  @SerializedName("taken_at_timestamp"              ) var takenAtTimestamp            : Int?                        = null,
  @SerializedName("edge_media_preview_like"         ) var edgeMediaPreviewLike        : EdgeMediaPreviewLike?       = EdgeMediaPreviewLike(),
  @SerializedName("edge_media_to_sponsor_user"      ) var edgeMediaToSponsorUser      : EdgeMediaToSponsorUser?     = EdgeMediaToSponsorUser(),
  @SerializedName("is_affiliate"                    ) var isAffiliate                 : Boolean?                    = null,
  @SerializedName("is_paid_partnership"             ) var isPaidPartnership           : Boolean?                    = null,
  @SerializedName("location"                        ) var location                    : String?                     = null,
  @SerializedName("nft_asset_info"                  ) var nftAssetInfo                : String?                     = null,
  @SerializedName("viewer_has_liked"                ) var viewerHasLiked              : Boolean?                    = null,
  @SerializedName("viewer_has_saved"                ) var viewerHasSaved              : Boolean?                    = null,
  @SerializedName("viewer_has_saved_to_collection"  ) var viewerHasSavedToCollection  : Boolean?                    = null,
  @SerializedName("viewer_in_photo_of_you"          ) var viewerInPhotoOfYou          : Boolean?                    = null,
  @SerializedName("viewer_can_reshare"              ) var viewerCanReshare            : Boolean?                    = null,
  @SerializedName("owner"                           ) var owner                       : Owner?                      = Owner(),
  @SerializedName("is_ad"                           ) var isAd                        : Boolean?                    = null,
  @SerializedName("edge_web_media_to_related_media" ) var edgeWebMediaToRelatedMedia  : EdgeWebMediaToRelatedMedia? = EdgeWebMediaToRelatedMedia(),
  @SerializedName("coauthor_producers"              ) var coauthorProducers           : ArrayList<Any>           = arrayListOf(),
  @SerializedName("pinned_for_users"                ) var pinnedForUsers              : ArrayList<Any>           = arrayListOf(),
  @SerializedName("encoding_status"                 ) var encodingStatus              : String?                     = null,
  @SerializedName("is_published"                    ) var isPublished                 : Boolean?                    = null,
  @SerializedName("product_type"                    ) var productType                 : String?                     = null,
  @SerializedName("title"                           ) var title                       : String?                     = null,
  @SerializedName("video_duration"                  ) var videoDuration               : Double?                     = null,
  @SerializedName("thumbnail_src"                   ) var thumbnailSrc                : String?                     = null,
  @SerializedName("clips_music_attribution_info"    ) var clipsMusicAttributionInfo   : ClipsMusicAttributionInfo?  = ClipsMusicAttributionInfo(),
  @SerializedName("edge_related_profiles"           ) var edgeRelatedProfiles         : EdgeRelatedProfiles?        = EdgeRelatedProfiles()

)