package com.centicbhaiya.getitsocial.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF8D08E0)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF2DAFF)
val md_theme_light_onPrimaryContainer = Color(0xFF2E004E)
val md_theme_light_secondary = Color(0xFF675A6E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEEDDF5)
val md_theme_light_onSecondaryContainer = Color(0xFF221829)
val md_theme_light_tertiary = Color(0xFF815155)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDADB)
val md_theme_light_onTertiaryContainer = Color(0xFF321015)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_outline = Color(0xFF7C757E)
val md_theme_light_inverseOnSurface = Color(0xFFF6EFF3)
val md_theme_light_inverseSurface = Color(0xFF322F33)
val md_theme_light_inversePrimary = Color(0xFFE1B6FF)
val md_theme_light_surfaceTint = Color(0xFF8D08E0)
val md_theme_light_outlineVariant = Color(0xFFCDC3CE)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFF7FC)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFE9DFEA)
val md_theme_light_onSurfaceVariant = Color(0xFF4B454D)

val md_theme_dark_primary = Color(0xFFE1B6FF)
val md_theme_dark_onPrimary = Color(0xFF4C007C)
val md_theme_dark_primaryContainer = Color(0xFF6C00AE)
val md_theme_dark_onPrimaryContainer = Color(0xFFF2DAFF)
val md_theme_dark_secondary = Color(0xFFD1C1D9)
val md_theme_dark_onSecondary = Color(0xFF372C3F)
val md_theme_dark_secondaryContainer = Color(0xFF4E4256)
val md_theme_dark_onSecondaryContainer = Color(0xFFEEDDF5)
val md_theme_dark_tertiary = Color(0xFFF4B7BB)
val md_theme_dark_onTertiary = Color(0xFF4C2529)
val md_theme_dark_tertiaryContainer = Color(0xFF663A3E)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDADB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE7E1E5)
val md_theme_dark_outline = Color(0xFF968E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val md_theme_dark_inversePrimary = Color(0xFF8D08E0)
val md_theme_dark_surfaceTint = Color(0xFFE1B6FF)
val md_theme_dark_outlineVariant = Color(0xFF4B454D)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF151316)
val md_theme_dark_onSurface = Color(0xFFCBC5C9)
val md_theme_dark_surfaceVariant = Color(0xFF4B454D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC3CE)


val seed = Color(0xFF9E2CF0)